### PR TITLE
iOS

### PR DESCRIPTION
**Pull request by josh**
Requires iOS 9 and Xcode 7 beta.

* [x] App Icon
* [ ] Launch Image
* [ ] App contents is just blank
* [x] Actually works!

/cc @dgraham

### CODE REVIEW

**Comment by dgraham** [comment]
We'll learn more as we go, but there may only be two states for the app:
1. The Safari extension it contains is enabled in Settings or
2. The extension is disabled and we can help enable it.

Here are some mocks for the two states. What do you think?

extension disabled
extension enabled

**Comment by dgraham** [comment]
For fun, here's some of the other ideas I explored with layout, shape, and color.

exploratory missions

**Comment by dgraham** [comment]
Here's a mock for the app icon. It maintains the shape and typography from the OS X Safari extension, inset into a round-rect with a red field for iOS.

red inset

**Comment by dgraham** [comment]
Here are a few more treatments of the same app icon shape just for fun. It's important that there's consistency between iOS and OS X, but these explore different colors and borders.

white inset

black inset

red inset

**Comment by josh** [comment]
Just posting what it currently looks like in the extensions settings page.

screen shot 2015-06-20 at 6 50 36 pm

**Comment by josh** [comment]
Reopened PR https://github.com/dgraham/Ka-Block/pull/3.

**Pull request closed without merging**
